"""\
Streamlit App — Berlin Smart Canopy
REAL DATA ONLY (2026-08-22) — see ml_engine.py's module docstring for what
changed and why. In short: the old per-PLZ "emissions" and "sealed surface"
numbers were entirely fabricated (no real PLZ-level source exists) and have
been removed rather than kept as always-fake placeholders; planting priority
is now ranked on real population + real tree data instead; and the old
RandomForest "2050 prediction" (trained on labels generated by its own
formula, i.e. not real) has been replaced with a transparent calculator that
applies the same growth formula directly, with no hidden training step.

Pages:
1) Urban Canopy Dashboard
   - Map: real district boundaries + real (partial) Bezirk CO2 data, real
     tree layer (heatmap or clustered points)
   - Table: PLZ areas ranked by real population vs. real tree coverage
2) Planting Calculator
   - Select a PLZ, add a virtual planting plan
   - Projects canopy absorption forward using a direct formula (no ML model)

Run:
    streamlit run app.py

Prerequisites:
    python build_real_plz_geojson.py
    python data_generator.py
    python ml_engine.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import pandas as pd
import geopandas as gpd
import joblib

import streamlit as st
import streamlit.components.v1 as components
import folium
from folium.plugins import MarkerCluster, HeatMap, Fullscreen
import altair as alt

PROJECT_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(PROJECT_ROOT))

from load_real_data import try_load_real_bezirk_emissions
from ml_engine import project_planting_scenario_tons


# ---------------------------------------------------------------------------
# Streamlit configuration
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Berlin Smart Canopy",
    page_icon="🌳",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ---------------------------------------------------------------------------
# Paths (relative to this app file)
# ---------------------------------------------------------------------------
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
MODELS_DIR = PROJECT_ROOT / "data" / "models"

RAW_TREES_CSV = DATA_RAW / "baumbestand_berlin.csv"
RAW_PLZ_GEOJSON = DATA_RAW / "berlin_plz.geojson"

# Real Berlin borough (Bezirk) boundaries — vendored static asset, not part of
# the regenerable data_generator.py/ml_engine.py pipeline. Used to label the
# map with real area names (Mitte, Pankow, ...) and to show real (partial)
# Bezirk-level CO2 data. See data/external/berlin_bezirke_source/PROVENANCE.md.
BEZIRKE_GEOJSON = PROJECT_ROOT / "data" / "external" / "berlin_bezirke_source" / "berliner-bezirke.geojson"

PLZ_FEATURES_GEOJSON = DATA_PROCESSED / "plz_features.geojson"
TREES_ENRICHED_PARQUET = DATA_PROCESSED / "trees_enriched.parquet"

KMEANS_PIPELINE_PATH = MODELS_DIR / "kmeans_plz_pipeline.joblib"
METADATA_PATH = MODELS_DIR / "model_metadata.joblib"


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _missing_artifacts() -> list[str]:
    # RAW_TREES_CSV/RAW_PLZ_GEOJSON are pipeline *inputs* (data_generator.py
    # stages them, ml_engine.py reads them to build the processed outputs
    # below) — nothing in app.py itself reads them at runtime. Gating on
    # their presence used to make the deployed app require files it never
    # actually opens; the four files below are the only ones it reads.
    required = [
        PLZ_FEATURES_GEOJSON,
        TREES_ENRICHED_PARQUET,
        KMEANS_PIPELINE_PATH,
        METADATA_PATH,
    ]
    return [str(p) for p in required if not p.exists()]


def _fmt_tons(x: float) -> str:
    return f"{x:,.0f} t"


def _fmt_tons_precise(x: float) -> str:
    return f"{x:,.2f} t"


def _fmt_rank(x) -> str:
    """priority_rank/cluster_label are NaN for any PLZ without a real
    population match (excluded from ranking rather than guessed) — show a
    dash instead of crashing on int(nan)."""
    return "—" if pd.isna(x) else str(int(x))


# Genus -> color, for coloring individual tree markers on the map. Covers the
# 15 real genus buckets from load_real_data.py plus the "Other" catch-all —
# a qualitative palette chosen for contrast against the Voyager basemap.
GENUS_COLORS = {
    "Quercus (Eiche)": "#8B4513",
    "Tilia (Linde)": "#2E7D32",
    "Acer (Ahorn)": "#E65100",
    "Platanus": "#00838F",
    "Betula": "#9E9E9E",
    "Fraxinus": "#558B2F",
    "Robinia (Robinie)": "#C0CA33",
    "Aesculus (Rosskastanie)": "#6D4C41",
    "Carpinus (Hainbuche)": "#00695C",
    "Pinus (Kiefer)": "#1B5E20",
    "Fagus (Buche)": "#BF360C",
    "Corylus (Hasel)": "#827717",
    "Prunus (Kirsche)": "#AD1457",
    "Populus (Pappel)": "#43A047",
    "Alnus (Erle)": "#4E342E",
    "Other": "#78909C",
}
DEFAULT_GENUS_COLOR = "#78909C"


# ---------------------------------------------------------------------------
# Cached loaders
# ---------------------------------------------------------------------------

@st.cache_data(show_spinner="Loading PLZ boundaries…")
def load_plz_features_geo() -> gpd.GeoDataFrame:
    gdf = gpd.read_file(PLZ_FEATURES_GEOJSON)
    if gdf.crs is None:
        gdf = gdf.set_crs("EPSG:4326", allow_override=True)
    else:
        gdf = gdf.to_crs("EPSG:4326")
    gdf["PLZ"] = gdf["PLZ"].astype(str)
    gdf["bezirk"] = gdf["bezirk"].fillna("—")
    return gdf


@st.cache_data(show_spinner="Loading tree inventory (691k rows, first load only)…")
def load_trees_enriched() -> pd.DataFrame:
    df = pd.read_parquet(TREES_ENRICHED_PARQUET)
    df["PLZ"] = df["PLZ"].astype(str)
    return df


@st.cache_data(show_spinner=False)
def load_bezirke() -> gpd.GeoDataFrame | None:
    """Real Berlin borough boundaries with real names, merged with real
    (partial — 2/12 boroughs as of this writing) Bezirk-level CO2 data.
    Returns None if the vendored boundary file isn't present (map still
    works, just without area-name labels)."""
    if not BEZIRKE_GEOJSON.exists():
        return None
    gdf = gpd.read_file(BEZIRKE_GEOJSON)
    if gdf.crs is None:
        gdf = gdf.set_crs("EPSG:4326", allow_override=True)
    else:
        gdf = gdf.to_crs("EPSG:4326")
    gdf["name"] = gdf["spatial_alias"]

    emissions_df = try_load_real_bezirk_emissions()
    if emissions_df is not None and len(emissions_df):
        gdf = gdf.merge(emissions_df.rename(columns={"bezirk": "name"}), on="name", how="left")
    else:
        gdf["total_co2_tons"] = np.nan
        gdf["year"] = np.nan

    gdf["co2_display"] = gdf.apply(
        lambda r: f"{r['total_co2_tons']:,.0f} t ({int(r['year'])})"
        if pd.notna(r["total_co2_tons"])
        else "not yet published",
        axis=1,
    )
    return gdf


@st.cache_resource(show_spinner="Loading models…")
def load_models() -> Tuple[object, dict]:
    kmeans_pipeline = joblib.load(KMEANS_PIPELINE_PATH)
    metadata = joblib.load(METADATA_PATH)
    return kmeans_pipeline, metadata


# ---------------------------------------------------------------------------
# Calculator helpers
# ---------------------------------------------------------------------------

def make_projection_curve(
    current_year: int,
    current_absorption_tons: float,
    projected_absorption_tons: float,
    horizon_year: int = 2050,
) -> pd.DataFrame:
    """Visualization-only curve between current and target year (saturating
    interpolation) — intermediate years are for the chart, not a second
    calculation."""
    years = np.arange(current_year, horizon_year + 1)
    t = (years - current_year) / max(horizon_year - current_year, 1)

    curve = (1 - np.exp(-3.2 * t)) / (1 - np.exp(-3.2))
    absorption = current_absorption_tons + curve * (projected_absorption_tons - current_absorption_tons)

    return pd.DataFrame({"year": years, "absorption_tons": absorption})


# ---------------------------------------------------------------------------
# App shell
# ---------------------------------------------------------------------------

st.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

    html, body, [class*="css"] { font-family: 'Inter', -apple-system, sans-serif; }

    :root {
        --canopy-green: #1B5E20;
        --canopy-green-light: #E8F5E9;
        --canopy-accent: #2E7D32;
        --canopy-ink: #1a1a1a;
        --canopy-muted: #6b7280;
    }

    .block-container { padding-top: 1.5rem; max-width: 1400px; }

    /* Hero header */
    .canopy-hero {
        background: linear-gradient(135deg, #1B5E20 0%, #2E7D32 55%, #43A047 100%);
        border-radius: 16px;
        padding: 28px 32px;
        margin-bottom: 18px;
        box-shadow: 0 4px 20px rgba(27, 94, 32, 0.25);
    }
    .canopy-hero h1 {
        color: white; font-size: 1.7rem; font-weight: 800; margin: 0 0 4px 0;
        letter-spacing: -0.02em;
    }
    .canopy-hero p { color: rgba(255,255,255,0.88); font-size: 0.95rem; margin: 0; }

    /* Provenance chips */
    .prov-row { display: flex; gap: 8px; margin-top: 14px; flex-wrap: wrap; }
    .prov-chip {
        display: inline-flex; align-items: center; gap: 6px;
        background: rgba(255,255,255,0.15); backdrop-filter: blur(4px);
        border: 1px solid rgba(255,255,255,0.25); border-radius: 999px;
        padding: 4px 12px; font-size: 0.78rem; color: white; font-weight: 500;
    }

    /* Metric cards */
    div[data-testid="stMetric"] {
        background: white; border: 1px solid #e5e7eb; border-radius: 14px;
        padding: 16px 18px 14px 18px; box-shadow: 0 1px 3px rgba(0,0,0,0.04);
        transition: box-shadow 0.15s ease, transform 0.15s ease;
    }
    div[data-testid="stMetric"]:hover {
        box-shadow: 0 6px 16px rgba(0,0,0,0.08); transform: translateY(-1px);
    }
    div[data-testid="stMetricLabel"] { font-weight: 600; color: var(--canopy-muted); }
    div[data-testid="stMetricValue"] { color: var(--canopy-ink); font-weight: 700; }

    /* Tabs — bigger, pill-styled, modern segmented control feel */
    .stTabs [data-baseweb="tab-list"] { gap: 4px; background: #f3f4f6; padding: 5px; border-radius: 12px; }
    .stTabs [data-baseweb="tab"] {
        border-radius: 9px; padding: 8px 18px; font-weight: 600; color: var(--canopy-muted);
    }
    .stTabs [aria-selected="true"] {
        background: white !important; color: var(--canopy-green) !important;
        box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    }
    /* Pill-style selection above already shows the active tab — hide
       baseweb's default underline/highlight bar so it doesn't clash.
       (Belt-and-suspenders: theme.toml also sets primaryColor to green,
       so even if this selector ever misses, the bar comes out on-brand
       instead of Streamlit's default red.) */
    .stTabs [data-baseweb="tab-highlight"] {
        background-color: transparent !important; box-shadow: none !important;
        visibility: hidden !important; height: 0 !important;
    }
    .stTabs [data-baseweb="tab-border"] { background-color: transparent !important; height: 0 !important; }

    /* Section headers */
    .canopy-section-title {
        font-size: 1.05rem; font-weight: 700; color: var(--canopy-ink);
        margin: 4px 0 10px 0; display: flex; align-items: center; gap: 8px;
    }

    div[data-testid="stDataFrame"] { border-radius: 12px; overflow: hidden; }
    </style>
    """,
    unsafe_allow_html=True,
)

missing = _missing_artifacts()
if missing:
    st.error("Required data/model artifacts are missing.")
    st.code(
        "python build_real_plz_geojson.py\n"
        "python data_generator.py\n"
        "python ml_engine.py\n"
        "streamlit run app.py\n",
        language="bash",
    )
    with st.expander("Missing files"):
        st.write(missing)
    st.stop()

plz_gdf = load_plz_features_geo()
trees_df = load_trees_enriched()
_, metadata = load_models()

current_year = int(metadata.get("current_year", pd.Timestamp.today().year))

# ---------------------------------------------------------------------------
# Hero header + data provenance chips
# ---------------------------------------------------------------------------
prov = metadata.get("data_provenance", {})
emis_cov = metadata.get("emissions_coverage", {})
rank_cov = metadata.get("priority_ranking_coverage", {})
_LABELS = {
    "real": "🟢 real",
    "partial": "🟠 partial",
    "none": "⚪ no data",
    "synthetic": "🟡 synthetic",
    "synthetic_grid": "🟡 synthetic",
}
emissions_chip = _LABELS.get(prov.get("emissions"), "⚪ unknown")
if prov.get("emissions") == "partial" and emis_cov:
    emissions_chip += f" ({emis_cov.get('real_boroughs', 0)}/{emis_cov.get('total_boroughs', 12)} boroughs)"

st.markdown(
    f"""
    <div class="canopy-hero">
        <h1>🌳 Berlin Smart Canopy</h1>
        <p>Where Berlin needs trees most, and which species to plant there — from real population, tree, and cited growth-rate data</p>
        <div class="prov-row">
            <span class="prov-chip">PLZ boundaries {_LABELS.get(prov.get('plz_boundaries'), '⚪ unknown')}</span>
            <span class="prov-chip">Trees {_LABELS.get(prov.get('trees'), '⚪ unknown')}</span>
            <span class="prov-chip">Population {_LABELS.get(prov.get('population'), '⚪ unknown')}</span>
            <span class="prov-chip">Emissions {emissions_chip}</span>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)
st.caption("See METHODOLOGY.md and data/external/real/BEZIRK_EMISSIONS_PROVENANCE.md for exact sources.")

with st.expander("ℹ️ About this project — tree equity, planting priority, and what's real"):
    n_ranked = rank_cov.get("ranked", "?")
    n_total = rank_cov.get("total", "?")
    n_bezirk_real = emis_cov.get("real_boroughs", 0)
    n_bezirk_total = emis_cov.get("total_boroughs", 12)
    real_bezirk_names = sorted(
        {str(b) for b in plz_gdf.loc[plz_gdf["bezirk_total_co2_tons"].notna(), "bezirk"].unique()}
    )
    real_bezirk_names_str = ", ".join(real_bezirk_names) if real_bezirk_names else "none"
    st.markdown(
        f"""
**What this is.** Berlin Smart Canopy answers two real-data questions behind the project's original
idea — where to plant, and what to plant. It ranks Berlin's postal-code (PLZ) areas by tree equity
— how many trees an area has per resident, using real population figures and Berlin's real tree
cadastre — to surface where planting would help the most people. It separately ranks tree species
by how much CO2 they sequester per tree, using real per-tree data and a cited growth-rate source,
to surface which species are worth prioritizing once you know where to plant. Carbon absorption
numbers throughout are a clearly-caveated estimate layered on top of real inputs (see the
methodology note below), not a claim of measured precision.

**The three tabs.**
- 🗺️ **Urban Canopy Dashboard** — a city-wide map (real district boundaries, real trees, real
  Bezirk-level CO2 data where published) and a table of the {n_total} real PLZ areas ranked by
  real population density vs. real trees-per-resident ({n_ranked}/{n_total} areas have a real
  population match and are ranked; the rest are shown but excluded from ranking rather than
  guessed).
- 🌳 **Species Carbon Ranking** — every species in the real tree cadastre, ranked by average CO2
  sequestered per tree per year, using real trunk diameter/age plus a cited (not invented)
  per-genus growth-rate source. Answers the project's original question directly: which species
  should future planting focus on.
- 🌱 **Planting Calculator** — pick a PLZ and a hypothetical planting plan (how many trees of
  which species), and see the projected change in that area's canopy carbon absorption. This is a
  direct calculation (see `ml_engine.project_planting_scenario_tons`), not a trained model — there
  was no real historical outcome data to train one on, so a transparent formula replaced it rather
  than pretending otherwise.

**Every input is real data now** (see the chips above): real Berlin postal-code boundaries, the
real tree cadastre ({len(trees_df):,} trees), and real population figures per PLZ. The one
exception is CO2 emissions: **Berlin does not publish a complete borough-level emissions
dataset** — confirmed via an official Berlin parliament written response, most boroughs have
neither measured nor published one. Only {n_bezirk_real} of {n_bezirk_total} boroughs
({real_bezirk_names_str}) have a real published figure, from different years — shown as real
data for those two, "not yet published" for the rest. Nothing is fabricated to fill that gap.

**A methodology caveat worth knowing:** tree carbon sequestration is computed from a proxy
allometric formula (age, trunk diameter, species) rather than a field-validated model like i-Tree
Eco — every *input* to that formula is real, but the conversion formula itself is an illustrative
estimate. Treat absolute absorption numbers as illustrative rather than authoritative; the
relative comparisons (which areas have fewer trees per resident, which species sequester more)
are the more trustworthy part. Full detail in `METHODOLOGY.md`.
        """
    )


tab_dashboard, tab_species, tab_calculator = st.tabs(
    ["🗺️  Urban Canopy Dashboard", "🌳  Species Carbon Ranking", "🌱  Planting Calculator"]
)


# ---------------------------------------------------------------------------
# Map builder — cached so it only rebuilds when a map control actually
# changes. Without this, Streamlit reruns the ENTIRE script (including this
# ~8,000-marker map) on every single interaction anywhere on the page —
# switching tabs, moving an unrelated slider, anything — which is what made
# the app feel slow.
#
# Two layers of caching:
# 1. This function returns the RENDERED HTML STRING (via m.get_root().render()),
#    not the folium.Map object. A folium Map is cheap to build but expensive
#    to serialize to HTML/JS — and the old code (st_folium(m, ...)) redid
#    that serialization on every single rerun even when `m` itself came from
#    cache, because st_folium re-renders its argument every call. Caching
#    the final HTML string skips that too.
# 2. We embed the cached HTML with st.components.v1.html() instead of
#    st_folium(). st_folium is a *bidirectional* component — clicking a
#    marker, panning, or zooming sends state back to Python and triggers a
#    full Streamlit rerun. Nothing in this app reads that return value, so
#    components.html() is a static embed instead: interacting with the map
#    (pan/zoom/click a cluster) no longer reruns the app at all.
#
# Leading-underscore params (_trees_render, _bezirke_gdf) are passed through
# but excluded from the cache key — they're already stable for the life of
# the session (loaded once via the cached loaders above), so hashing them on
# every call would defeat the point.
# ---------------------------------------------------------------------------


@st.cache_data(show_spinner="Building map…")
def _build_dashboard_map_html(
    show_bezirk_labels: bool,
    show_bezirk_emissions: bool,
    tree_render_mode: str,
    heatmap_metric: str,
    max_tree_points: int,
    _trees_render: pd.DataFrame,
    _bezirke_gdf,
) -> str:
    # Map — CartoDB Voyager: a labeled, colorful basemap (street names, place
    # names, transit) rather than the near-blank "positron" style, so the map
    # reads as a real map of Berlin rather than a flat analytical overlay.
    berlin_center = [52.5200, 13.4050]
    m = folium.Map(
        location=berlin_center,
        zoom_start=11,
        tiles="https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png",
        attr='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
        control_scale=True,
    )

    # Real district (Bezirk) outlines + permanent name labels, optionally
    # tinted where real CO2 data has been published (2/12 boroughs).
    if _bezirke_gdf is not None and (show_bezirk_labels or show_bezirk_emissions):

        def _style(feature):
            has_co2 = feature["properties"].get("total_co2_tons") is not None
            return {
                "color": "#1B5E20",
                "weight": 2,
                "fillOpacity": 0.28 if (show_bezirk_emissions and has_co2) else 0,
                "fillColor": "#F4511E" if (show_bezirk_emissions and has_co2) else "#1B5E20",
                "dashArray": "4 3",
            }

        tooltip_fields = ["name"]
        tooltip_aliases = ["District"]
        if show_bezirk_emissions:
            tooltip_fields.append("co2_display")
            tooltip_aliases.append("Real CO2 data")

        folium.GeoJson(
            _bezirke_gdf,
            name="District boundaries",
            style_function=_style,
            tooltip=folium.GeoJsonTooltip(fields=tooltip_fields, aliases=tooltip_aliases, sticky=False),
        ).add_to(m)

        if show_bezirk_labels:
            for _, row in _bezirke_gdf.iterrows():
                centroid = row.geometry.centroid
                folium.map.Marker(
                    [centroid.y, centroid.x],
                    icon=folium.DivIcon(
                        html=(
                            '<div style="font-family:Inter,sans-serif; font-weight:700; font-size:12.5px; '
                            'color:#1B5E20; text-shadow: -1px -1px 0 #fff, 1px -1px 0 #fff, '
                            '-1px 1px 0 #fff, 1px 1px 0 #fff, 0 0 6px #fff; white-space:nowrap; '
                            f'pointer-events:none;">{row["name"]}</div>'
                        ),
                        icon_size=(0, 0),
                    ),
                ).add_to(m)

    # Tree layer — clustered points by default (colored by genus), heatmap as
    # an alternative for a fast, density-only view.
    #
    # The heatmap used to always weight by annual_sequestration_kg with
    # Leaflet's default blue->cyan->lime->yellow->red gradient and no legend
    # — two colors on the map (a rainbow with no key) that nothing explained.
    # Now: the user picks what the color represents (heatmap_metric), the
    # gradient is a single on-brand green->amber ramp (darker = more, no
    # "red = danger" implication for what is a good-news metric), and a
    # legend box on the map spells out what light vs. dark means.
    if tree_render_mode.startswith("Heatmap"):
        if heatmap_metric.startswith("Carbon"):
            weights = _trees_render["annual_sequestration_kg"].clip(0.2, 50.0).to_numpy()
            legend_title = "Carbon absorption intensity (proxy)"
            legend_low, legend_high = "Lower", "Higher"
        else:
            weights = np.ones(len(_trees_render))
            legend_title = "Tree density"
            legend_low, legend_high = "Fewer trees", "More trees"

        heat_gradient = {
            0.2: "#e8f5e9",
            0.4: "#a5d6a7",
            0.6: "#4caf50",
            0.8: "#f9a825",
            1.0: "#e65100",
        }
        heat_data = [
            [float(lat), float(lon), float(w)]
            for lat, lon, w in zip(_trees_render["latitude"], _trees_render["longitude"], weights)
        ]
        HeatMap(
            heat_data,
            name="Trees (heatmap)",
            radius=12,
            blur=14,
            min_opacity=0.25,
            gradient=heat_gradient,
        ).add_to(m)

        legend_html = f"""
        <div style="position: fixed; bottom: 24px; left: 24px; z-index: 9999;
                    background: white; border-radius: 10px; padding: 10px 14px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.25);
                    font-family: Inter, -apple-system, sans-serif; font-size: 12px;
                    color: #1a1a1a; width: 200px;">
          <div style="font-weight: 700; margin-bottom: 6px;">{legend_title}</div>
          <div style="height: 10px; border-radius: 5px; background: linear-gradient(
              to right, #e8f5e9, #a5d6a7, #4caf50, #f9a825, #e65100);"></div>
          <div style="display: flex; justify-content: space-between; margin-top: 4px; color: #6b7280;">
            <span>{legend_low}</span><span>{legend_high}</span>
          </div>
        </div>
        """
        m.get_root().html.add_child(folium.Element(legend_html))
    else:
        # Custom cluster badges in the canopy-green palette (instead of
        # Leaflet's default blue/yellow/orange) sized by how many trees they
        # contain, for a cleaner, on-brand look at a glance.
        cluster_icon_js = """
        function(cluster) {
            var count = cluster.getChildCount();
            var size = count < 50 ? 32 : count < 500 ? 40 : 50;
            var shade = count < 50 ? '#66BB6A' : count < 500 ? '#2E7D32' : '#1B5E20';
            return L.divIcon({
                html: '<div style="background:' + shade + '; color:white; border-radius:50%; ' +
                      'width:' + size + 'px; height:' + size + 'px; display:flex; align-items:center; ' +
                      'justify-content:center; font-family:Inter,sans-serif; font-weight:700; ' +
                      'font-size:' + (size > 40 ? 13 : 11) + 'px; border:2px solid white; ' +
                      'box-shadow:0 2px 6px rgba(0,0,0,0.35);">' + count + '</div>',
                className: '', iconSize: L.point(size, size)
            });
        }
        """
        cluster = MarkerCluster(
            name="Trees (clustered points)",
            icon_create_function=cluster_icon_js,
            # chunkedLoading batches marker insertion across animation frames
            # instead of blocking the browser tab while it clusters thousands
            # of points in one go — this is what makes the first paint of the
            # tree layer feel slow with a few thousand markers.
            chunkedLoading=True,
            chunkInterval=100,
            chunkDelay=10,
        )
        for _, r in _trees_render.iterrows():
            genus = str(r["species"])
            color = GENUS_COLORS.get(genus, DEFAULT_GENUS_COLOR)
            folium.CircleMarker(
                location=[float(r["latitude"]), float(r["longitude"])],
                radius=3,
                weight=0,
                fill=True,
                fill_opacity=0.85,
                color=color,
                popup=folium.Popup(
                    f'<div style="font-family:Inter,sans-serif; min-width:160px;">'
                    f'<div style="background:{color}; color:white; padding:4px 8px; border-radius:6px 6px 0 0; '
                    f'font-weight:700; font-size:13px;">{genus}</div>'
                    f'<div style="padding:8px; font-size:12.5px; line-height:1.6;">'
                    f'Age: {int(r["tree_age_years"])} years<br>'
                    f'Sequestration: {float(r["annual_sequestration_kg"]):.2f} kg CO₂/yr<br>'
                    f'PLZ: {r["PLZ"]}'
                    f'</div></div>',
                    max_width=260,
                ),
            ).add_to(cluster)
        cluster.add_to(m)

    Fullscreen(position="topleft").add_to(m)
    folium.LayerControl(collapsed=False).add_to(m)
    return m.get_root().render()


# ---------------------------------------------------------------------------
# Sidebar — map layer controls (shared by the dashboard tab)
# ---------------------------------------------------------------------------

st.sidebar.header("Map layers")

show_bezirk_labels = st.sidebar.checkbox(
    "Show district (Bezirk) names",
    value=True,
    help="Outlines Berlin's 12 real boroughs and labels each with its name (e.g. Mitte, Neukölln).",
)
show_bezirk_emissions = st.sidebar.checkbox(
    "Show real Bezirk CO2 data (2/12 boroughs)",
    value=False,
    help="Tints the 2 boroughs (Charlottenburg-Wilmersdorf, Pankow) that have published a real "
    "CO2 figure. Berlin hasn't published borough-level emissions for the other 10 — there's no "
    "fabricated number filling that gap, the map just shows what's real.",
)

st.sidebar.divider()
st.sidebar.subheader("Tree layer")
tree_render_mode = st.sidebar.selectbox(
    "Style",
    ["Clustered points", "Heatmap"],
    index=0,
    help="Clustered points: individual trees grouped into badges that expand as you zoom in, colored "
    "by species (hover/click a dot for details) — good for exploring specific areas. Heatmap: a "
    "single-color density glow (see the 'Heatmap shows' option and the legend on the map) — good "
    "for a quick citywide glance.",
)

heatmap_metric = "Tree density (where trees are concentrated)"
if tree_render_mode.startswith("Heatmap"):
    heatmap_metric = st.sidebar.selectbox(
        "Heatmap shows",
        [
            "Tree density (where trees are concentrated)",
            "Carbon absorption intensity (proxy, kg/yr)",
        ],
        index=0,
        help="Tree density: darker/warmer = more trees in that spot, regardless of size or species — "
        "the simplest read. Carbon absorption intensity: darker/warmer = more estimated CO₂ absorbed "
        "there combined (bigger/older trees and denser clusters both push this up) — a proxy formula, "
        "not a measurement. Either way: light green = low, dark green = medium, amber/orange = "
        "highest — see the legend box in the bottom-left of the map.",
    )

max_tree_points = st.sidebar.slider(
    "Max trees to render (sampling for performance)",
    min_value=500,
    max_value=30000,
    value=8000,
    step=500,
    help="The tree inventory has 690k+ real trees — rendering all of them at once would be slow in "
    "the browser, so the map shows a random sample of this size. Metrics and tables above always use "
    "the full dataset regardless of this setting.",
)

# Sample only for map layers (metrics use full dataset)
trees_render = trees_df
if len(trees_render) > max_tree_points:
    trees_render = trees_render.sample(max_tree_points, random_state=42)


# ---------------------------------------------------------------------------
# Page 1: Dashboard
# ---------------------------------------------------------------------------

with tab_dashboard:
    total_absorption = float(plz_gdf["total_canopy_co2_absorption_tons"].fillna(0).sum())
    total_population = float(plz_gdf["einwohner"].fillna(0).sum())
    n_bezirk_real = emis_cov.get("real_boroughs", 0)
    n_bezirk_total = emis_cov.get("total_boroughs", 12)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric(
        "Trees in inventory",
        f"{len(trees_df):,}",
        help="Real trees from the Berlin tree cadastre (Baumkataster).",
    )
    c2.metric(
        "Annual canopy absorption (proxy)",
        _fmt_tons_precise(total_absorption),
        help="Estimated CO₂ absorbed per year by the current (real) tree inventory, from a proxy "
        "allometric formula (age, trunk diameter, species) — not a validated forestry model. See "
        "the About section above.",
    )
    c3.metric(
        "Real population covered",
        f"{total_population:,.0f}",
        help=f"Sum of real per-PLZ population figures ({rank_cov.get('ranked', '?')}/"
        f"{rank_cov.get('total', '?')} PLZ areas matched to a real population row).",
    )
    c4.metric(
        "Boroughs with real CO2 data",
        f"{n_bezirk_real}/{n_bezirk_total}",
        help="Berlin has not published a complete borough-level emissions dataset. This counts "
        "how many of the 12 boroughs have a real, published figure — see the map toggle below.",
    )

    st.divider()

    # Map is built by a cached function (see _build_dashboard_map_html above)
    # so it only rebuilds when a map control changes, not on every rerun.
    bezirke_gdf = load_bezirke()
    if show_bezirk_labels and bezirke_gdf is None:
        st.info(
            f"District name labels need {BEZIRKE_GEOJSON.relative_to(PROJECT_ROOT)}, which isn't present — "
            "map still works without it."
        )

    map_html = _build_dashboard_map_html(
        show_bezirk_labels,
        show_bezirk_emissions,
        tree_render_mode,
        heatmap_metric,
        max_tree_points,
        _trees_render=trees_render,
        _bezirke_gdf=bezirke_gdf,
    )

    st.markdown('<div class="canopy-section-title">🗺️ Interactive map</div>', unsafe_allow_html=True)
    # Static embed (not st_folium) — panning, zooming, and clicking markers/
    # clusters no longer trigger a Streamlit rerun, since nothing in this
    # app reads click feedback from the map.
    components.html(map_html, height=640, scrolling=False)

    st.markdown("#### High-Priority Planting Zones (Top 10)")
    st.caption(
        "Ranked by real population density vs. real trees-per-resident — areas with the most "
        "people and the fewest trees relative to them rank highest."
    )
    ranked = plz_gdf.drop(columns="geometry").dropna(subset=["priority_rank"]).copy()
    ranked["priority_rank"] = ranked["priority_rank"].astype(int)
    ranked["cluster_label"] = ranked["cluster_label"].astype(int)
    top = ranked.sort_values(["priority_rank", "PLZ"]).head(10)[
        [
            "PLZ",
            "bezirk",
            "priority_rank",
            "cluster_label",
            "population_density",
            "trees_per_1000_residents",
            "tree_count",
            "total_canopy_co2_absorption_tons",
        ]
    ]
    st.dataframe(
        top,
        use_container_width=True,
        hide_index=True,
        column_config={
            "PLZ": st.column_config.TextColumn("PLZ"),
            "bezirk": st.column_config.TextColumn("Area (district)"),
            "population_density": st.column_config.NumberColumn("Pop. density (/km²)", format="%.0f"),
            "trees_per_1000_residents": st.column_config.NumberColumn("Trees / 1,000 residents", format="%.1f"),
            "tree_count": st.column_config.NumberColumn("Tree count"),
            "total_canopy_co2_absorption_tons": st.column_config.NumberColumn("Absorption (t/yr, proxy)", format="%.2f"),
        },
    )
    if len(plz_gdf) > len(ranked):
        st.caption(
            f"{len(plz_gdf) - len(ranked)} PLZ area(s) excluded from ranking — no real population match."
        )

    with st.expander("Interpretation notes"):
        st.write(
            "- Priority rank combines two real inputs: higher population density and fewer real "
            "trees per 1,000 residents both push an area's rank up (z-scored and summed).\n"
            "- Tree sequestration is computed via a proxy allometric equation applied to real "
            "tree data, not a validated city-forestry model — treat absolute tons as illustrative, "
            "not authoritative. See METHODOLOGY.md.\n"
            "- CO2 emissions are shown at Bezirk (borough) level, and only for the 2 boroughs "
            "Berlin has actually published a figure for — turn on 'Show real Bezirk CO2 data' on "
            "the map above."
        )


# ---------------------------------------------------------------------------
# Species Carbon Ranking — this was the project's original starting idea:
# which tree species sequester the most CO2, so future planting can focus on
# those species. Computed directly from real per-tree data (species, trunk
# diameter, planting year) already in trees_df — no new data source needed.
# ---------------------------------------------------------------------------

with tab_species:
    st.subheader("Species Carbon Ranking")
    st.write(
        "Which tree species in Berlin's real inventory sequester the most CO₂ per tree, on "
        "average, each year — so future planting can prioritize the species that pull the most "
        f"weight. Computed from {len(trees_df):,} real trees: real species, real trunk diameter, "
        "real planting year."
    )

    species_summary = (
        trees_df.groupby("species", as_index=False)
        .agg(
            tree_count=("tree_id", "count"),
            avg_annual_co2_kg=("annual_sequestration_kg", "mean"),
            total_annual_co2_tons=("annual_sequestration_kg", lambda s: float(s.sum()) / 1000.0),
            avg_age_years=("tree_age_years", "mean"),
            avg_trunk_diameter_cm=("trunk_diameter_cm", "mean"),
        )
        .sort_values("avg_annual_co2_kg", ascending=False)
        .reset_index(drop=True)
    )

    st.markdown('<div class="canopy-section-title">📊 Average CO₂ sequestered per tree, by species</div>', unsafe_allow_html=True)
    chart_species = (
        alt.Chart(species_summary)
        .mark_bar()
        .encode(
            x=alt.X("avg_annual_co2_kg:Q", title="Avg. CO₂ per tree (kg/year, proxy formula)"),
            y=alt.Y("species:N", sort="-x", title=None),
            color=alt.Color(
                "species:N",
                scale=alt.Scale(domain=list(GENUS_COLORS.keys()), range=list(GENUS_COLORS.values())),
                legend=None,
            ),
            tooltip=[
                alt.Tooltip("species:N", title="Species"),
                alt.Tooltip("tree_count:Q", title="Trees in inventory", format=","),
                alt.Tooltip("avg_annual_co2_kg:Q", title="Avg. kg CO₂/yr per tree", format=".2f"),
                alt.Tooltip("avg_age_years:Q", title="Avg. age (yrs)", format=".0f"),
                alt.Tooltip("avg_trunk_diameter_cm:Q", title="Avg. trunk diameter (cm)", format=".0f"),
            ],
        )
        .properties(height=420)
    )
    st.altair_chart(chart_species, use_container_width=True)

    st.caption(
        "Bars reflect both the species' growth-rate class (see below) and the real average age/"
        "trunk diameter of that species' specimens actually in the ground in Berlin — a species "
        "with a fast growth-rate class but mostly young, thin specimens can still rank below an "
        "older-growing species with many mature trees."
    )

    st.dataframe(
        species_summary,
        use_container_width=True,
        hide_index=True,
        column_config={
            "species": st.column_config.TextColumn("Species"),
            "tree_count": st.column_config.NumberColumn("Trees in inventory", format="%d"),
            "avg_annual_co2_kg": st.column_config.NumberColumn("Avg. kg CO₂/yr per tree", format="%.2f"),
            "total_annual_co2_tons": st.column_config.NumberColumn("Total t CO₂/yr (this species)", format="%.1f"),
            "avg_age_years": st.column_config.NumberColumn("Avg. age (yrs)", format="%.0f"),
            "avg_trunk_diameter_cm": st.column_config.NumberColumn("Avg. trunk diameter (cm)", format="%.0f"),
        },
    )

    with st.expander("Where do these per-species numbers come from?"):
        st.markdown(
            "**Real inputs, cited growth-rate classes.** Every tree behind this ranking is real "
            "(species, trunk diameter, planting year from Berlin's tree cadastre). Each species is "
            "also assigned a growth-rate class — Hardwood/Conifer × Slow/Moderate/Fast — from the "
            "USDA Forest Service / EPA-published McPherson & Nowak method for estimating urban tree "
            "carbon sequestration, which is backed by a measured age-vs-sequestration table (this "
            "replaced an earlier version of this project that used hand-picked, uncited per-species "
            "multipliers — see `ml_engine.py`'s `SPECIES_GROWTH_FACTOR` for the full source mapping "
            "and `METHODOLOGY.md` for the change history).\n\n"
            "**What's still an approximation.** The source table classifies *genera*, not Berlin's "
            "exact specimens — real growth rate varies between species within a genus (not every "
            "oak grows at the same rate), and 2 of the 16 genus buckets here (Carpinus, Corylus) "
            "aren't in that source table, so they fall back to general arboricultural consensus "
            "instead of a cited figure. The kg-CO₂-per-tree conversion itself (age, trunk diameter, "
            "growth class → kg/year) is still the project's proxy allometric formula, not a "
            "field-validated method like i-Tree Eco. Treat this as a well-sourced *relative* "
            "ranking — which species are worth prioritizing — rather than an authoritative absolute "
            "number for any one species."
        )

    st.caption(
        "Use the Planting Calculator tab to model adding more of a top-ranked species to a "
        "specific high-priority area from the Dashboard tab."
    )


# ---------------------------------------------------------------------------
# Page 2: Planting Calculator
# ---------------------------------------------------------------------------

with tab_calculator:
    st.subheader("Planting Calculator")
    st.write(
        "Select a PLZ and add a virtual planting plan. This projects that area's canopy carbon "
        "absorption forward to a target year using a direct formula — not a trained model."
    )
    with st.expander("How does this calculation work?"):
        st.markdown(
            "`ml_engine.project_planting_scenario_tons()` takes today's real canopy absorption for "
            "the selected PLZ (from real tree data), grows it forward on the same saturating curve "
            "used elsewhere in this project, and adds the estimated contribution of the new trees "
            "in your plan at the age they'd reach by the target year — using the same per-species "
            "allometric formula as everywhere else in the app "
            "(`estimate_annual_sequestration_kg`/`SPECIES_GROWTH_FACTOR` in `ml_engine.py`).\n\n"
            "**This used to be a RandomForest model.** It was removed: its training labels were "
            "generated by this exact same formula, so it was learning to reproduce a calculation "
            "rather than predicting a real outcome — there's no real longitudinal dataset of "
            "\"we planted N trees and Y years later canopy absorption was Z\" to train on. Calling "
            "the formula directly is more honest about what this number is: a calculation, not a "
            "forecast, and it's fully deterministic (same inputs always give the same output — no "
            "hidden randomness)."
        )

    plz_table = plz_gdf.drop(columns="geometry").copy().sort_values(["priority_rank", "PLZ"], na_position="last")

    left, right = st.columns([0.38, 0.62], vertical_alignment="top")

    with left:
        st.markdown("### 1) Select target area")
        selected_plz = st.selectbox(
            "PLZ",
            options=plz_table["PLZ"].astype(str).tolist(),
            index=0,
            format_func=lambda plz: (
                f"{plz} — {plz_table.set_index('PLZ').loc[plz, 'bezirk']}"
                if plz in plz_table["PLZ"].values
                else plz
            ),
            help="Postal-code areas are ordered by priority rank where available (highest-priority first).",
        )

        sel = plz_table.loc[plz_table["PLZ"].astype(str) == str(selected_plz)].iloc[0]

        st.markdown("### 2) Current snapshot (real data)")
        a, b = st.columns(2)
        a.metric("Priority rank", _fmt_rank(sel["priority_rank"]))
        b.metric("Cluster", _fmt_rank(sel["cluster_label"]))

        c, d = st.columns(2)
        pop_density = sel.get("population_density")
        trees_per_1000 = sel.get("trees_per_1000_residents")
        c.metric("Pop. density (/km²)", f"{pop_density:,.0f}" if pd.notna(pop_density) else "—")
        d.metric("Trees / 1,000 residents", f"{trees_per_1000:,.1f}" if pd.notna(trees_per_1000) else "—")

        e, f = st.columns(2)
        e.metric("Tree count", f"{int(sel['tree_count']):,}")
        f.metric("Absorption now (t/yr)", _fmt_tons_precise(float(sel["total_canopy_co2_absorption_tons"])))

        bezirk_co2 = sel.get("bezirk_total_co2_tons")
        bezirk_year = sel.get("bezirk_emissions_year")
        if pd.notna(bezirk_co2):
            st.caption(
                f"Borough ({sel['bezirk']}) real CO2 total: {bezirk_co2:,.0f} t ({int(bezirk_year)}) — "
                "Bezirk-level, not specific to this PLZ."
            )
        else:
            st.caption(f"Borough ({sel['bezirk']}) CO2 data: not yet published by Berlin.")

        st.divider()
        st.markdown("### 3) Virtual planting plan")

        st.caption("How many new trees of each species/genus to add to this PLZ in the scenario.")
        plantings: Dict[str, int] = {}
        for sp in metadata["species_cols"]:
            plantings[sp] = st.slider(
                f"Plant {sp}",
                min_value=0,
                max_value=12000,
                value=0,
                step=250,
            )

        target_year = st.slider("Project to year", min_value=current_year + 1, max_value=2060, value=2050, step=1)

        st.caption("This is a planning tool. For production, enforce area/soil/utility constraints per PLZ.")

    with right:
        st.markdown(f"### {target_year} projection and trajectory")

        current_abs = float(sel["total_canopy_co2_absorption_tons"])

        try:
            projected_abs = project_planting_scenario_tons(
                current_absorption_tons=current_abs,
                plantings=plantings,
                current_year=current_year,
                target_year=target_year,
            )
        except Exception as ex:
            st.error("Calculation failed.")
            st.exception(ex)
            st.stop()

        proj = make_projection_curve(
            current_year=current_year,
            current_absorption_tons=current_abs,
            projected_absorption_tons=projected_abs,
            horizon_year=target_year,
        )

        added_tons = projected_abs - current_abs
        pct_change = (added_tons / current_abs * 100.0) if current_abs > 0 else float("nan")

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Absorption now", _fmt_tons_precise(current_abs))
        m2.metric(
            f"Projected absorption ({target_year})",
            _fmt_tons_precise(projected_abs),
            help="Direct calculation for the planting plan on the left — see 'How does this "
            "calculation work?' above.",
        )
        m3.metric("Added by this plan", _fmt_tons_precise(added_tons))
        m4.metric("% change", f"{pct_change:,.1f}%" if pd.notna(pct_change) else "—")

        st.markdown(f"#### Canopy absorption trajectory to {target_year} (tons/year)")
        chart_abs = (
            alt.Chart(proj)
            .mark_area(opacity=0.25, color="#2E7D32", line={"color": "#1B5E20", "strokeWidth": 3})
            .encode(
                x=alt.X("year:Q", title="Year"),
                y=alt.Y("absorption_tons:Q", title="Canopy absorption (tons/year)"),
                tooltip=["year:Q", alt.Tooltip("absorption_tons:Q", format=",.2f")],
            )
            .properties(height=320)
        )
        st.altair_chart(chart_abs, use_container_width=True)

        with st.expander("Calculation inputs"):
            st.write(
                f"- Current year: {current_year} → target year: {target_year} ({target_year - current_year} years)\n"
                f"- Current absorption (real trees, proxy formula): {current_abs:,.2f} t/yr\n"
                "- New trees in this plan: "
                + (", ".join(f"{sp}: {n:,}" for sp, n in plantings.items() if n > 0) or "none")
            )

        with st.expander("Modeling notes"):
            st.write(
                "- This is a deterministic formula, not a trained model — same inputs always give "
                "the same output, and there's no synthetic training data behind it.\n"
                "- Intermediate years on the chart are interpolated for visualization (not a "
                "second calculation).\n"
                "- Emissions aren't projected here — Berlin's real CO2 data is Bezirk-level and "
                "only covers 2 of 12 boroughs, so a per-PLZ 'net footprint' would mix a real "
                "borough figure with fabricated precision. See the Dashboard tab for what real "
                "emissions data is available."
            )
