"""\
Feature engineering + planting-priority engine for "Berlin Smart Canopy".
REAL DATA ONLY — see the "What changed" note below.

What this script does:
1) Loads raw datasets from data/raw (real PLZ boundaries + real tree cadastre,
   both written by data_generator.py) plus real population and real (partial)
   Bezirk emissions data from data/external/real/ (via load_real_data.py).
2) Engineers botanical proxy features per real tree:
   - tree_age_years = current_year - planting_year
   - annual_sequestration_kg (proxy allometric function using age, trunk diameter, species)
   - current_storage_kg (simple cumulative proxy)
   These stay a proxy/estimate — see estimate_annual_sequestration_kg's docstring — but they're
   applied to real per-tree data, not fabricated inputs.
3) Aggregates by PLZ, joins real population and (where available) real Bezirk-level emissions.
4) Trains Model A (unsupervised): KMeans on real inputs only — population density, tree count,
   and trees-per-1000-residents — to cluster PLZ areas and rank planting priority.
5) Saves processed datasets and the trained clustering model.

What changed (2026-08-22): this used to also train a RandomForest ("Model B") to predict 2050
canopy absorption, but its training labels were generated by a deterministic formula applied to
itself — there was no real outcome data to learn from, so it could never be more than a fast
replica of that formula wearing an ML label. It's been replaced with
project_planting_scenario_tons() below: the SAME formula, called directly, with no model file,
no synthetic training set, and no hidden randomness. Likewise the old per-PLZ "emissions" and
"sealed_surface_ratio" fields were entirely fabricated (no real PLZ-level source exists) and have
been removed outright rather than left in as placeholders — see METHODOLOGY.md for the full
history and BEZIRK_EMISSIONS_PROVENANCE.md for why real emissions data only covers 2 of 12
boroughs.

What changed (2026-08-22, part 2): SPECIES_GROWTH_FACTOR's per-genus multipliers used to be
hand-picked numbers with no citation. They're now derived from the USDA Forest Service /
EPA-published McPherson & Nowak method ("Carbon Dioxide Reduction Through Urban Forestry" /
"Method for Calculating Carbon Sequestration by Trees in Urban and Suburban Settings"), which
classifies tree genera into Hardwood/Conifer x Slow/Moderate/Fast growth-rate classes backed by
an actual measured age-vs-sequestration table. See the dict below for the per-genus source and
the resulting reordering (e.g. Populus and Tilia move up — poplars and lindens are genuinely fast
growers in that table; Fagus and Aesculus move down — beech and horsechestnut are classified
Slow). This directly answers the project's original question — which species sequester the most,
so planting can prioritize them — with a cited relative ranking instead of an invented one. It's
still a genus-level approximation (real growth rate varies by individual species within a genus,
and 2 of the 16 genera aren't in the source table — see the per-entry notes), applied on top of
real per-tree age and trunk-diameter data, not a field re-measurement of Berlin's actual trees.

Geospatial: EPSG:4326 throughout.

Usage:
    python ml_engine.py
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Tuple, List
import math

import numpy as np
import pandas as pd
import geopandas as gpd
import joblib

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans


@dataclass(frozen=True)
class Paths:
    project_root: Path = Path(__file__).resolve().parent

    data_raw: Path = project_root / "data" / "raw"
    data_processed: Path = project_root / "data" / "processed"
    models_dir: Path = project_root / "data" / "models"

    trees_csv: Path = data_raw / "baumbestand_berlin.csv"
    plz_geojson: Path = data_raw / "berlin_plz.geojson"
    bezirke_geojson: Path = (
        project_root / "data" / "external" / "berlin_bezirke_source" / "berliner-bezirke.geojson"
    )

    trees_enriched_parquet: Path = data_processed / "trees_enriched.parquet"
    plz_features_geojson: Path = data_processed / "plz_features.geojson"

    kmeans_pipeline_path: Path = models_dir / "kmeans_plz_pipeline.joblib"
    metadata_path: Path = models_dir / "model_metadata.joblib"


def _ensure_dirs(paths: Paths) -> None:
    paths.data_processed.mkdir(parents=True, exist_ok=True)
    paths.models_dir.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Botanical proxy equations — applied to real per-tree data (age, trunk
# diameter, species), but the equation itself is still an illustrative proxy,
# not derived from a validated forestry model like i-Tree Eco. See
# METHODOLOGY.md. This is a modeling-method caveat, not a data-fabrication
# one: every input the formula runs on is real.
# ---------------------------------------------------------------------------
# Source: McPherson & Nowak (USDA Forest Service), as published by the EPA in
# "Method for Calculating Carbon Sequestration by Trees in Urban and Suburban
# Settings" — Table 1 classifies ~80 common urban tree species into
# Hardwood/Conifer x Slow/Moderate/Fast growth-rate classes; Table 2 gives
# measured annual carbon-sequestration-by-age for each class. The ratios below
# are each class's average annual increment relative to Hardwood-Moderate
# (=1.0), averaged across the table's published age rows (5-59 years).
# Hardwood-Slow ~0.47x, Hardwood-Moderate 1.0x, Hardwood-Fast ~1.77x,
# Conifer-Slow ~0.33x, Conifer-Moderate ~0.74x, Conifer-Fast ~1.37x.
#
# Per-genus source note (genus-level pick where a genus has multiple
# species/classes in Table 1 — see METHODOLOGY.md for the full mapping):
#   Quercus (oak): Table 1 lists most oaks Moderate-Fast -> Hardwood-Moderate
#   Tilia (linden/lime): littleleaf linden = Hardwood-Fast in Table 1
#   Acer (maple): Norway/red maple = Hardwood-Moderate in Table 1
#   Platanus (plane/sycamore): London plane = Hardwood-Fast in Table 1
#   Betula (birch): paper/white birch = Hardwood-Moderate in Table 1
#   Fraxinus (ash): green/white ash = Hardwood-Fast in Table 1
#   Robinia (black locust): Hardwood-Fast in Table 1
#   Aesculus (horsechestnut/buckeye): Hardwood-Slow in Table 1
#   Carpinus (hornbeam): NOT in Table 1 -> general arboricultural consensus
#     (slow-to-moderate grower) -> Hardwood-Slow
#   Pinus (pine): common Berlin/Brandenburg pine = Scots pine = "Scotch" in
#     Table 1 -> Conifer-Moderate
#   Fagus (beech): Table 1 -> Hardwood-Slow
#   Corylus (hazel): NOT in Table 1 (shrub-form genus, not a canonical US
#     street tree) -> conservative Hardwood-Moderate default
#   Prunus (cherry/plum): Table 1 -> Hardwood-Fast
#   Populus (poplar): Table 1 mostly Fast (well-documented as one of the
#     fastest-growing tree genera) -> Hardwood-Fast
#   Alnus (alder): Table 1 -> Hardwood-Fast
#   Other: mixed/unidentified species in the cadastre -> Hardwood-Moderate
SPECIES_GROWTH_FACTOR: Dict[str, float] = {
    "Quercus (Eiche)": 1.00,
    "Tilia (Linde)": 1.77,
    "Acer (Ahorn)": 1.00,
    "Platanus": 1.77,
    "Betula": 1.00,
    "Fraxinus": 1.77,
    "Robinia (Robinie)": 1.77,
    "Aesculus (Rosskastanie)": 0.47,
    "Carpinus (Hainbuche)": 0.47,
    "Pinus (Kiefer)": 0.74,
    "Fagus (Buche)": 0.47,
    "Corylus (Hasel)": 1.00,
    "Prunus (Kirsche)": 1.77,
    "Populus (Pappel)": 1.77,
    "Alnus (Erle)": 1.77,
    "Other": 1.00,
}


def estimate_annual_sequestration_kg(
    species: pd.Series,
    trunk_diameter_cm: pd.Series,
    age_years: pd.Series,
) -> pd.Series:
    """Return kg CO2/year per tree (proxy, not a botanical truth model)."""
    s_factor = species.map(SPECIES_GROWTH_FACTOR).fillna(0.9).astype(float)

    age = age_years.clip(lower=1).astype(float)
    age_term = 1.0 - np.exp(-age / 18.0)

    d = trunk_diameter_cm.clip(lower=2.0, upper=160.0).astype(float)
    diam_term = d**1.35

    annual_kg = 0.045 * s_factor * age_term * diam_term
    return annual_kg.clip(lower=0.2, upper=120.0)


def estimate_current_storage_kg(annual_kg: pd.Series, age_years: pd.Series) -> pd.Series:
    """Simple cumulative proxy (kg CO2 stored)."""
    age = age_years.clip(lower=1).astype(float)
    return (0.55 * annual_kg * age).clip(lower=1.0)


def enrich_trees(trees_df: pd.DataFrame, current_year: int) -> pd.DataFrame:
    df = trees_df.copy()

    df["PLZ"] = df["PLZ"].astype(str)
    df["planting_year"] = pd.to_numeric(df["planting_year"], errors="coerce")
    df["trunk_diameter_cm"] = pd.to_numeric(df["trunk_diameter_cm"], errors="coerce")
    df["latitude"] = pd.to_numeric(df["latitude"], errors="coerce")
    df["longitude"] = pd.to_numeric(df["longitude"], errors="coerce")

    df = df.dropna(
        subset=["tree_id", "species", "planting_year", "trunk_diameter_cm", "latitude", "longitude", "PLZ"]
    ).copy()

    df["tree_age_years"] = (current_year - df["planting_year"].astype(int)).clip(lower=1)

    df["annual_sequestration_kg"] = estimate_annual_sequestration_kg(
        df["species"], df["trunk_diameter_cm"], df["tree_age_years"]
    )
    df["current_storage_kg"] = estimate_current_storage_kg(df["annual_sequestration_kg"], df["tree_age_years"])

    return df


# ---------------------------------------------------------------------------
# PLZ -> Bezirk spatial join. Real district boundaries + real PLZ boundaries
# both exist; Berlin's real (partial) emissions data is published at Bezirk
# level, so this is how it gets attached to PLZ rows for display.
# ---------------------------------------------------------------------------

def load_bezirke(paths: Paths) -> gpd.GeoDataFrame | None:
    if not paths.bezirke_geojson.exists():
        return None
    gdf = gpd.read_file(paths.bezirke_geojson)
    if gdf.crs is None:
        gdf = gdf.set_crs("EPSG:4326", allow_override=True)
    else:
        gdf = gdf.to_crs("EPSG:4326")
    gdf["name"] = gdf["spatial_alias"]
    return gdf


def plz_to_bezirk(plz_gdf: gpd.GeoDataFrame, bezirke_gdf: gpd.GeoDataFrame) -> Dict[str, str]:
    """Maps each PLZ to the real Bezirk its centroid falls in (nearest-Bezirk
    fallback for any centroid that lands just outside every polygon due to
    boundary-simplification edge artifacts)."""
    centroids = plz_gdf[["PLZ", "geometry"]].copy()
    centroids["geometry"] = centroids.geometry.centroid
    districts = bezirke_gdf[["name", "geometry"]]

    joined = gpd.sjoin(centroids, districts, how="left", predicate="within")
    joined = joined[~joined.index.duplicated(keep="first")]

    unmatched = joined["name"].isna()
    if unmatched.any():
        nearest = gpd.sjoin_nearest(centroids.loc[unmatched], districts, how="left")
        nearest = nearest[~nearest.index.duplicated(keep="first")]
        joined.loc[unmatched, "name"] = nearest["name"]

    return dict(zip(joined["PLZ"].astype(str), joined["name"]))


# ---------------------------------------------------------------------------
# PLZ feature table — real trees + real population + real (partial) Bezirk
# emissions. No fabricated column survives from the old synthetic version:
# total_co2_tons and sealed_surface_ratio are gone entirely rather than kept
# around as always-empty placeholders.
# ---------------------------------------------------------------------------

def build_plz_features(
    all_plz: List[str],
    trees_enriched: pd.DataFrame,
    population_df: pd.DataFrame,
    bezirk_by_plz: Dict[str, str],
    bezirk_emissions_df: pd.DataFrame | None,
) -> pd.DataFrame:
    trees_enriched = trees_enriched.copy()
    trees_enriched["PLZ"] = trees_enriched["PLZ"].astype(str)

    canopy_agg = (
        trees_enriched.groupby("PLZ", as_index=False)
        .agg(
            total_canopy_co2_absorption_tons=("annual_sequestration_kg", lambda s: float(s.sum()) / 1000.0),
            total_current_storage_tons=("current_storage_kg", lambda s: float(s.sum()) / 1000.0),
            tree_count=("tree_id", "count"),
            mean_tree_age=("tree_age_years", "mean"),
            mean_trunk_diameter_cm=("trunk_diameter_cm", "mean"),
        )
    )

    species_counts = (
        trees_enriched.pivot_table(
            index="PLZ", columns="species", values="tree_id", aggfunc="count", fill_value=0
        ).reset_index()
    )
    species_counts.columns = [str(c) for c in species_counts.columns]

    # Base = every real PLZ boundary, so areas with zero trees in the cadastre
    # export still show up (rather than silently vanishing from the table).
    plz_features = pd.DataFrame({"PLZ": [str(p) for p in all_plz]})
    plz_features = plz_features.merge(canopy_agg, on="PLZ", how="left")
    plz_features = plz_features.merge(species_counts, on="PLZ", how="left")
    plz_features = plz_features.merge(
        population_df[["PLZ", "einwohner", "population_density"]], on="PLZ", how="left"
    )

    plz_features["total_canopy_co2_absorption_tons"] = plz_features["total_canopy_co2_absorption_tons"].fillna(0.0)
    plz_features["total_current_storage_tons"] = plz_features["total_current_storage_tons"].fillna(0.0)
    plz_features["tree_count"] = plz_features["tree_count"].fillna(0).astype(int)
    plz_features["mean_tree_age"] = plz_features["mean_tree_age"].fillna(0.0)
    plz_features["mean_trunk_diameter_cm"] = plz_features["mean_trunk_diameter_cm"].fillna(0.0)

    for sp in SPECIES_GROWTH_FACTOR.keys():
        if sp not in plz_features.columns:
            plz_features[sp] = 0
        else:
            plz_features[sp] = plz_features[sp].fillna(0)

    # Real, but only defined where real population matched — NaN elsewhere
    # rather than a fabricated stand-in.
    plz_features["trees_per_1000_residents"] = np.where(
        plz_features["einwohner"].fillna(0) > 0,
        plz_features["tree_count"] / (plz_features["einwohner"] / 1000.0),
        np.nan,
    )

    plz_features["bezirk"] = plz_features["PLZ"].map(bezirk_by_plz)
    if bezirk_emissions_df is not None and len(bezirk_emissions_df):
        plz_features = plz_features.merge(
            bezirk_emissions_df.rename(
                columns={"total_co2_tons": "bezirk_total_co2_tons", "year": "bezirk_emissions_year"}
            ),
            on="bezirk",
            how="left",
        )
    else:
        plz_features["bezirk_total_co2_tons"] = np.nan
        plz_features["bezirk_emissions_year"] = np.nan

    return plz_features


# ---------------------------------------------------------------------------
# Model A: Unsupervised clustering + priority ranking — real inputs only.
# Areas with more residents per tree rank as higher planting priority; areas
# missing real population data are excluded from ranking (left as NaN)
# rather than filled with a guess.
# ---------------------------------------------------------------------------

PRIORITY_FEATURE_COLS = ["population_density", "tree_count", "trees_per_1000_residents"]


def train_kmeans(plz_features: pd.DataFrame, n_clusters: int = 4) -> Tuple[Pipeline, List[str], pd.Index]:
    valid = plz_features.dropna(subset=PRIORITY_FEATURE_COLS)
    k = max(1, min(n_clusters, len(valid)))

    X = valid[PRIORITY_FEATURE_COLS].astype(float)
    pipe = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("kmeans", KMeans(n_clusters=k, n_init="auto", random_state=42)),
        ]
    )
    if len(valid):
        pipe.fit(X)
    return pipe, PRIORITY_FEATURE_COLS, valid.index


def compute_priority_score(plz_features: pd.DataFrame) -> pd.Series:
    """Higher = more residents per tree = higher planting priority. Both
    inputs are real (population_density, trees_per_1000_residents)."""
    z = {}
    for c in ["population_density", "trees_per_1000_residents"]:
        v = plz_features[c].astype(float)
        std = v.std(ddof=0)
        z[c] = (v - v.mean()) / std if std > 1e-9 else v * 0.0
    return z["population_density"] - z["trees_per_1000_residents"]


# ---------------------------------------------------------------------------
# Planting-scenario calculator (replaces the old "Model B" RandomForest).
# This is a direct, deterministic application of the same allometric growth
# formula used above — no training set, no model file, no randomness. It's
# a calculation, not a trained forecast, and the app labels it that way.
# ---------------------------------------------------------------------------

def _annual_kg_per_new_tree_at_age(species: str, age_years: int) -> float:
    s_factor = SPECIES_GROWTH_FACTOR.get(species, 0.9)
    age_term = 1.0 - math.exp(-max(age_years, 1) / 18.0)
    diam_cm = min(55.0, 8.0 + (age_years**0.75) * 1.6 * s_factor)
    annual_kg = 0.045 * s_factor * age_term * (diam_cm**1.35)
    return float(np.clip(annual_kg, 0.2, 120.0))


def project_planting_scenario_tons(
    current_absorption_tons: float,
    plantings: Dict[str, int],
    current_year: int,
    target_year: int = 2050,
) -> float:
    """Projected tons CO2/year absorbed by target_year: today's real trees'
    absorption grown forward on the same saturating curve used elsewhere in
    this project, plus the estimated contribution of newly planted trees at
    the age they'd reach by target_year. Deterministic — same inputs always
    give the same output, and there's no hidden training data behind it."""
    years = max(target_year - current_year, 1)

    baseline_multiplier = 1.0 + 0.22 * (1.0 - math.exp(-years / 18.0))
    baseline = current_absorption_tons * baseline_multiplier

    added_tons = 0.0
    for sp, n in plantings.items():
        per_tree_kg = _annual_kg_per_new_tree_at_age(sp, years)
        added_tons += (per_tree_kg * max(int(n), 0)) / 1000.0

    return float(max(0.0, baseline + added_tons))


def main() -> None:
    paths = Paths()
    _ensure_dirs(paths)

    required = [paths.trees_csv, paths.plz_geojson]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing raw dataset(s). Run data_generator.py first.\n" + "\n".join(missing)
        )

    current_year = int(pd.Timestamp.today().year)

    trees_df = pd.read_csv(paths.trees_csv)
    plz_gdf = gpd.read_file(paths.plz_geojson)
    plz_gdf["PLZ"] = plz_gdf["PLZ"].astype(str)
    if plz_gdf.crs is None:
        plz_gdf = plz_gdf.set_crs("EPSG:4326", allow_override=True)
    else:
        plz_gdf = plz_gdf.to_crs("EPSG:4326")

    # Enrich & persist trees
    trees_enriched = enrich_trees(trees_df, current_year=current_year)
    trees_enriched.to_parquet(paths.trees_enriched_parquet, index=False)

    # Real population — required. This is the real signal the priority
    # ranking runs on now, replacing the old fabricated emissions+sealing
    # formula.
    from load_real_data import (
        try_load_real_population,
        try_load_real_bezirk_emissions,
        find_real_trees_csv,
        REAL_POPULATION_CSV,
    )

    population_df = try_load_real_population(plz_gdf)
    if population_df is None:
        raise FileNotFoundError(
            f"{REAL_POPULATION_CSV} not found. Real population data is required — it's the "
            "input the priority ranking (trees per resident) is built on. See load_real_data.py."
        )

    bezirke_gdf = load_bezirke(paths)
    bezirk_by_plz = plz_to_bezirk(plz_gdf, bezirke_gdf) if bezirke_gdf is not None else {}
    bezirk_emissions_df = try_load_real_bezirk_emissions()

    plz_features = build_plz_features(
        all_plz=list(plz_gdf["PLZ"]),
        trees_enriched=trees_enriched,
        population_df=population_df,
        bezirk_by_plz=bezirk_by_plz,
        bezirk_emissions_df=bezirk_emissions_df,
    )

    # Model A: cluster + rank on real inputs only. PLZ rows without a real
    # population match are excluded from ranking (NaN), not guessed.
    kmeans_pipe, kmeans_feature_cols, ranked_index = train_kmeans(plz_features, n_clusters=4)
    plz_features["cluster_label"] = np.nan
    plz_features["priority_score"] = np.nan
    if len(ranked_index):
        plz_features.loc[ranked_index, "cluster_label"] = kmeans_pipe.predict(
            plz_features.loc[ranked_index, kmeans_feature_cols].astype(float)
        )
        plz_features.loc[ranked_index, "priority_score"] = compute_priority_score(
            plz_features.loc[ranked_index]
        )
    plz_features["priority_rank"] = plz_features["priority_score"].rank(ascending=False, method="dense")

    n_ranked = len(ranked_index)
    n_total = len(plz_features)
    print(f"Priority ranking computed for {n_ranked}/{n_total} PLZ areas "
          f"({n_total - n_ranked} excluded — no real population match).")

    # Geo-join for mapping
    plz_geo = plz_gdf.merge(plz_features, on="PLZ", how="left")
    plz_geo = plz_geo.set_crs("EPSG:4326", allow_override=True)
    plz_geo.to_file(paths.plz_features_geojson, driver="GeoJSON")

    # Persist
    joblib.dump(kmeans_pipe, paths.kmeans_pipeline_path)

    n_bezirk_real = int(bezirk_emissions_df["total_co2_tons"].notna().sum()) if bezirk_emissions_df is not None else 0
    n_bezirk_total = int(len(bezirk_emissions_df)) if bezirk_emissions_df is not None else 0

    metadata = {
        "current_year": current_year,
        "kmeans_feature_cols": kmeans_feature_cols,
        "species_cols": list(SPECIES_GROWTH_FACTOR.keys()),
        "data_provenance": {
            "plz_boundaries": "real" if len(plz_gdf) != 30 else "synthetic_grid",
            "trees": "real" if find_real_trees_csv() is not None else "synthetic",
            "population": "real",
            "emissions": "partial" if n_bezirk_real else "none",
        },
        "emissions_coverage": {
            "real_boroughs": n_bezirk_real,
            "total_boroughs": n_bezirk_total,
        },
        "priority_ranking_coverage": {"ranked": n_ranked, "total": n_total},
        "notes": (
            "Botanical sequestration equations are still an illustrative proxy (see "
            "estimate_annual_sequestration_kg's docstring), applied to real per-tree data. "
            "The planting-scenario projection (project_planting_scenario_tons) is a direct, "
            "deterministic application of that same formula — not a trained model — since "
            "there is no real longitudinal outcome data to train one on. Emissions are real "
            "Bezirk-level BISKO figures where published (2 of 12 boroughs as of this run) and "
            "left as 'no data' elsewhere, rather than filled in with a fabricated PLZ-level "
            "number. See METHODOLOGY.md and BEZIRK_EMISSIONS_PROVENANCE.md."
        ),
    }
    joblib.dump(metadata, paths.metadata_path)

    print("Saved artifacts:")
    print(f"- {paths.trees_enriched_parquet}")
    print(f"- {paths.plz_features_geojson}")
    print(f"- {paths.kmeans_pipeline_path}")
    print(f"- {paths.metadata_path}")


if __name__ == "__main__":
    main()
